package org.omg.IOP;


/**
* org/omg/IOP/RMICustomMaxStreamFormat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/wsjdk/Corretto8Src/installers/windows/zip/corretto-build/buildRoot/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Friday, July 14, 2023 7:33:31 PM UTC
*/

public interface RMICustomMaxStreamFormat
{

  /**
     * Identifies a CDR encapsulation of the RMICustomMaxStreamFormat
     * service context which contains a single byte specifying
     * the client's maximum RMI-IIOP stream format version.
     *
     * See Java to IDL ptc/02-01-12 1.4.12.
     */
  public static final int value = (int)(17L);
}
