package org.omg.PortableInterceptor;


/**
* org/omg/PortableInterceptor/NON_EXISTENT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from c:/wsjdk/Corretto8Src/installers/windows/zip/corretto-build/buildRoot/corba/src/share/classes/org/omg/PortableInterceptor/Interceptors.idl
* Friday, July 14, 2023 7:33:31 PM UTC
*/

public interface NON_EXISTENT
{

  /** Object adapter state indicating that the adapter has been destroyed.
   */
  public static final short value = (short)(4);
}
